# SPDX-FileCopyrightText: Copyright (C) 2022 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

line-length: false

ul-indent:
  indent: 4

# Allow bare URLs since we use magiclink to convert bare URLs automatically to links
MD034: false

# to use collapsible sections
no-inline-html: false

# Need to disable in order to support PyMdown Tabbed extension
# See: https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
MD046: false

# mkdocstring crossreference support is not compatible with this rule
# see: https://mkdocstrings.github.io/usage/#cross-references
MD052: false
