# Generated by Django 3.2.15 on 2022-09-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    """Initial migration that creates export report permissions dummy."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportReportPerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Export Report',
                'verbose_name_plural': 'Export Reports',
                'permissions': (('view_report', 'View Export Reports Permission'), ('launch_report', 'Launch Export Reports Permission')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
