# Generated by Django 4.1.10 on 2023-08-30 19:45

from django.db import migrations


class Migration(migrations.Migration):
    """Rename the ExportReportPermission model to Questionnaire."""

    dependencies = [
        ('questionnaires', '0002_questionnaire_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExportReportPermission',
            new_name='Questionnaire',
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={
                'default_permissions': (),
                'managed': False,
                'permissions': (('export_report', 'Export Reports'),),
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
            },
        ),
    ]
