# Generated by Django 4.1.13 on 2024-01-29 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Change `on_delete` to `CASCADE` for the `user` field in `QuestionnaireProfile`."""

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaires', '0003_rename_exportreportpermission_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireprofile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
    ]
