# Generated by Django 3.2.13 on 2022-06-08 17:41

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def create_default_report_templates(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """
    Provide initial report templates for the `ReportTemplate` model (questionnaires and weights).

    Args:
        apps: instance of [Apps][django.apps.registry.Apps] containing historical models that match the operation's place in the project history
        schema_editor: [SchemaEditor][django.db.backends.base.schema.BaseDatabaseSchemaEditor] instance
    """
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    # https://docs.djangoproject.com/en/4.0/ref/migration-operations/#runpython
    ReportTemplate = apps.get_model('report_settings', 'ReportTemplate')  # noqa: N806
    ReportTemplate.objects.bulk_create([
        ReportTemplate(
            name='Questionnaires',
            name_en='Questionnaires',
            name_fr='Questionnaires',
            logo='logo_sfHmtLV.png',
            logo_en='logo_sfHmtLV.png',
            logo_fr='logo_YECnCWG.png',
            header='Completed and reported questionnaires by patient',
            header_en='Completed and reported questionnaires by patient',
            header_fr='Questionnaires remplis et déclarés par le patient',
            slug='questionnaires',
            favicon='fas fa-clipboard-check',
        ),
        ReportTemplate(
            name='Weights',
            name_en='Weights',
            name_fr='Poids',
            logo='logo_ZocWHDn.png',
            logo_en='logo_ZocWHDn.png',
            logo_fr='logo_Ufqfrgw.png',
            header='Patient weight and height list',
            header_en='Patient weight and height list',
            header_fr='Liste des poids et tailles du patient',
            slug='weights',
            favicon='fas fa-weight',
        ),
    ])


class Migration(migrations.Migration):
    """Initial migration that creates the `ReportTemplate` model."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('name_en', models.CharField(max_length=25, null=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=25, null=True, verbose_name='Name')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo')),
                ('logo_en', models.ImageField(null=True, upload_to='', verbose_name='Logo')),
                ('logo_fr', models.ImageField(null=True, upload_to='', verbose_name='Logo')),
                ('header', models.CharField(max_length=50, verbose_name='Header')),
                ('header_en', models.CharField(max_length=50, null=True, verbose_name='Header')),
                ('header_fr', models.CharField(max_length=50, null=True, verbose_name='Header')),
                ('slug', models.SlugField(unique=True)),
                ('favicon', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
            },
        ),
        migrations.RunPython(create_default_report_templates),
    ]
