# Generated by Django 4.1.2 on 2022-10-21 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0007_patient_hin_to_ramq"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthDataStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_data_store",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Data Store",
                "verbose_name_plural": "Health Data Stores",
            },
        ),
        migrations.CreateModel(
            name="QuantitySample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("value", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("HR", "Heart Rate (bpm)"),
                            ("HRV", "Heart Rate Variability (ms))"),
                            ("SPO2", "Oxygen Saturation (%)"),
                            ("BM", "Body Mass (kg)"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "data_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quantity_samples",
                        to="health_data.healthdatastore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quantity Sample",
                "verbose_name_plural": "Quantity Samples",
            },
        ),
    ]
