# Generated by Django 3.2.16 on 2022-11-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quantitysample',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['HR', 'HRV', 'SPO2', 'BM'])), name='health_data_quantitysample_type_valid'),
        ),
    ]
