# Generated by Django 3.2.16 on 2023-01-23 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Change `QuantitySample.patient` to `ForeignKey` to allow more than one sample."""

    dependencies = [
        ('patients', '0016_add_manage_relationshiptype_permission'),
        ('health_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantitysample',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_samples', to='patients.patient', verbose_name='Patient'),
        ),
    ]
