# Generated by Django 4.1.9 on 2023-07-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add systolic and diastolic blood pressure types."""

    dependencies = [
        ('health_data', '0002_quantitysample_patient_foreignkey'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quantitysample',
            name='health_data_quantitysample_type_valid',
        ),
        migrations.AlterField(
            model_name='quantitysample',
            name='type',
            field=models.CharField(choices=[('BM', 'Body Mass (kg)'), ('TMP', 'Body Temperature (°C)'), ('HR', 'Heart Rate (bpm)'), ('HRV', 'Heart Rate Variability (ms)'), ('SPO2', 'Oxygen Saturation (%)'), ('BPS', 'Blood Pressure Systolic (mmHg)'), ('BPD', 'Blood Pressure Diastolic (mmHg)')], max_length=4, verbose_name='Type'),
        ),
        migrations.AddConstraint(
            model_name='quantitysample',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['BM', 'TMP', 'HR', 'HRV', 'SPO2', 'BPS', 'BPD'])), name='health_data_quantitysample_type_valid'),
        ),
    ]
