# SPDX-FileCopyrightText: Copyright (C) 2022 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 4.0.3 on 2022-04-21 14:07

from django.db import migrations, models

import opal.users.models


class Migration(migrations.Migration):
    """
    Add user type to User model.

    Add proxy models for user type ClinicalStaff and Caregiver.
    """

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[],
            options={
                'verbose_name': 'Caregiver',
                'verbose_name_plural': 'Caregivers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', opal.users.models.CaregiverManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalStaff',
            fields=[],
            options={
                'verbose_name': 'Clinical Staff Member',
                'verbose_name_plural': 'Clinical Staff',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', opal.users.models.ClinicalStaffManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(
                choices=[('CLINICAL', 'Clinical Staff'), ('CAREGIVER', 'Caregiver')],
                default='CLINICAL',
                max_length=10,
                verbose_name='Type',
            ),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(
                check=models.Q(('type__in', ['CLINICAL', 'CAREGIVER'])), name='users_user_type_valid'
            ),
        ),
    ]
