# Generated by Django 4.0.3 on 2022-04-29 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add optional phone number to `User` model."""

    dependencies = [
        ('users', '0003_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Write in E.164 format (+[countryCode][phoneNumber]), for example +15141234567', max_length=16, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{6,14}$')], verbose_name='Phone Number'),
        ),
    ]
