# Generated by Django 4.1.13 on 2024-01-17 18:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    """Prototype migration."""

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0025_add_lab_result_delay_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(verbose_name='Last Login')),
                ('count_logins', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count Logins')),
                ('count_checkins', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count Checkins')),
                ('count_documents', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count Documents')),
                ('count_educational_materials', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count Educational Materials')),
                ('count_feedback', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count Feedbacks')),
                ('count_questionnaires', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count Questionnaires')),
                ('count_update_security_answers', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count Security Answer Updates')),
                ('count_update_passwords', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count Password Updates')),
                ('count_labs', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count Labs')),
                ('device_ios', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='IOS Devices')),
                ('device_android', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Android Devices')),
                ('device_browser', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Browser Devices')),
                ('date_added', models.DateField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('action_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User who triggered this action')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Patient')),
                ('user_relationship_to_patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.relationship', verbose_name='Relationship between user and patient')),
            ],
            options={
                'verbose_name': 'User App Activity',
                'verbose_name_plural': 'User App Activities',
            },
        ),
        migrations.CreateModel(
            name='PatientDemographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('U', 'Unknown')], max_length=1, verbose_name='Sex')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=2, verbose_name='Language')),
                ('access_level', models.IntegerField(verbose_name='Access Level')),
                ('blocked_status', models.BinaryField(verbose_name='Blocked Status')),
                ('status_reason', models.CharField(max_length=256, verbose_name='Status Reason')),
                ('completed_registration', models.CharField(max_length=3, verbose_name='Completed Registration')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Subject Patient')),
            ],
            options={
                'verbose_name': 'Patient Demographic',
                'verbose_name_plural': 'Patient Demographics',
            },
        ),
        migrations.CreateModel(
            name='PatientDataReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_appointment', models.DateTimeField(null=True, verbose_name='Next Appointment')),
                ('last_appointment_received', models.DateTimeField(verbose_name='Last Appointment Received')),
                ('appointments_received', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Appointments Received')),
                ('last_document_received', models.DateTimeField(verbose_name='Last Document Received')),
                ('documents_received', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Documents Received')),
                ('last_educational_materials_received', models.DateTimeField(verbose_name='Last Educational Materials Received')),
                ('educational_materials_received', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Educational Materials Received')),
                ('last_questionnaire_received', models.DateTimeField(verbose_name='Last Questionnaire Received')),
                ('questionnaires_received', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Questionnaires Received')),
                ('last_lab_received', models.DateTimeField(verbose_name='Last Lab Received')),
                ('labs_received', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Labs Received')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Patient Data Received',
                'verbose_name_plural': 'Patient Data Received Records',
            },
        ),
    ]
