# Generated by Django 4.2.11 on 2024-04-24 19:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    """Split chart data storage from user app data storage to reduce data redundancy."""

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0025_add_lab_result_delay_fields'),
        ('usage_statistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyuserappactivity',
            name='count_checkins',
        ),
        migrations.RemoveField(
            model_name='dailyuserappactivity',
            name='count_documents',
        ),
        migrations.RemoveField(
            model_name='dailyuserappactivity',
            name='count_educational_materials',
        ),
        migrations.RemoveField(
            model_name='dailyuserappactivity',
            name='count_labs',
        ),
        migrations.RemoveField(
            model_name='dailyuserappactivity',
            name='count_questionnaires_complete',
        ),
        migrations.RemoveField(
            model_name='dailyuserappactivity',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='dailyuserappactivity',
            name='user_relationship_to_patient',
        ),
        migrations.AlterField(
            model_name='dailyuserappactivity',
            name='action_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_user_app_activities', to=settings.AUTH_USER_MODEL, verbose_name='User who triggered this action'),
        ),
        migrations.CreateModel(
            name='DailyUserPatientActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_checkins', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count Checkins')),
                ('count_documents', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count Documents')),
                ('count_educational_materials', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count Educational Materials')),
                ('count_questionnaires_complete', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count Questionnaires')),
                ('count_labs', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count Labs')),
                ('date_added', models.DateField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('action_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_patient_activities', to=settings.AUTH_USER_MODEL, verbose_name='User who triggered this action')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_patient_activities', to='patients.patient', verbose_name='Patient')),
                ('user_relationship_to_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_patient_activities', to='patients.relationship', verbose_name='Relationship between user and patient')),
            ],
            options={
                'verbose_name': 'User Patient Activity',
                'verbose_name_plural': 'User Patient Activities',
                'indexes': [models.Index(fields=['date_added'], name='usage_stati_date_ad_549bd8_idx')],
            },
        ),
    ]
