# Generated by Django 4.2.11 on 2024-05-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    """Alter the statitics table to allowed the null value in the field."""

    dependencies = [
        ('usage_statistics', '0002_split_user_app_activity_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypatientdatareceived',
            name='last_appointment_received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Appointment Received'),
        ),
        migrations.AlterField(
            model_name='dailypatientdatareceived',
            name='last_document_received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Document Received'),
        ),
        migrations.AlterField(
            model_name='dailypatientdatareceived',
            name='last_educational_material_received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Educational Material Received'),
        ),
        migrations.AlterField(
            model_name='dailypatientdatareceived',
            name='last_lab_received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Lab Received'),
        ),
        migrations.AlterField(
            model_name='dailypatientdatareceived',
            name='last_questionnaire_received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Questionnaire Received'),
        ),
        migrations.AlterField(
            model_name='dailypatientdatareceived',
            name='next_appointment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Next Appointment'),
        ),
    ]
