# Generated by Django 4.2.11 on 2024-05-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """Rename date_added field to action_date to avoid ambiguity."""

    dependencies = [
        ('usage_statistics', '0002_split_user_app_activity_model'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailypatientdatareceived',
            name='usage_stati_date_ad_9d6318_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailyuserappactivity',
            name='usage_stati_date_ad_ed9ba6_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailyuserpatientactivity',
            name='usage_stati_date_ad_549bd8_idx',
        ),
        migrations.RemoveField(
            model_name='dailypatientdatareceived',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='dailyuserappactivity',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='dailyuserpatientactivity',
            name='date_added',
        ),
        migrations.AddField(
            model_name='dailypatientdatareceived',
            name='action_date',
            field=models.DateField(default=None, verbose_name='Action Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyuserappactivity',
            name='action_date',
            field=models.DateField(default=None, verbose_name='Action Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyuserpatientactivity',
            name='action_date',
            field=models.DateField(default=None, verbose_name='Action Date'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='dailypatientdatareceived',
            index=models.Index(fields=['action_date'], name='usage_stati_action__0e9f20_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyuserappactivity',
            index=models.Index(fields=['action_date'], name='usage_stati_action__9fe04d_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyuserpatientactivity',
            index=models.Index(fields=['action_date'], name='usage_stati_action__6efa5b_idx'),
        ),
    ]
