# Generated by Django 3.2.13 on 2022-05-06 20:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):
    """Initial migration that adds the patient model."""

    initial = True

    dependencies = [
        ('users', '0005_caregiverprofile'),
        ('hospital_settings', '0006_relationshiptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last Name')),
                ('birth_day', models.DateField()),
                ('legacy_id', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Legacy ID')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PEN', 'PENDING'), ('CON', 'CONFIRMED'), ('DEN', 'DENIED'), ('EXP', 'EXPIRED'), ('REP', 'EXPIRED')], default='PEN', max_length=3, verbose_name='Relationship Status')),
                ('request_date', models.DateField(verbose_name='Relationship Request Date')),
                ('start_date', models.DateField(verbose_name='Relationship Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Relationship End Date')),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='users.caregiverprofile', verbose_name='Caregiver')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='patients.patient', verbose_name='Patient')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='hospital_settings.relationshiptype', verbose_name='Relationship Type')),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='caregivers',
            field=models.ManyToManyField(related_name='patients', through='patients.Relationship', to='users.CaregiverProfile', verbose_name='Caregivers'),
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['PEN', 'CON', 'DEN', 'EXP', 'REP'])), name='patients_relationship_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lt', django.db.models.expressions.F('end_date'))), name='patients_relationship_date_valid'),
        ),
    ]
