# Generated by Django 3.2.13 on 2022-05-24 13:58

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    """Update some fields for patient model."""

    dependencies = [
        ('patients', '0002_patient_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='day_of_birth',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2022, 5, 24), verbose_name='Patient Date of Birth'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Last Name'),
        ),
    ]
