# Generated by Django 3.2.13 on 2022-05-30 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Create table for HospitalPatient model."""

    dependencies = [
        ('hospital_settings', '0005_add_site_direction_url'),
        ('patients', '0003_adjust_patient_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(max_length=20, verbose_name='MRN')),
                ('is_active', models.SmallIntegerField(default='1', verbose_name='Is Active')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_patients', to='patients.patient', verbose_name='Patient')),
                ('site', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_patients', to='hospital_settings.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Hospital Patient',
                'verbose_name_plural': 'Hospital Patients',
                'unique_together': {('patient', 'site', 'mrn')},
            },
        ),
    ]
