# Generated by Django 3.2.14 on 2022-07-15 19:44

from django.db import migrations


class Migration(migrations.Migration):
    """Patient migration."""

    dependencies = [
        ('patients', '0005_alter_hospitalpatient_site'),
        ('patients', '0005_patient_add_insurance_sex_fields'),
    ]

    operations = [
    ]
