# Generated by Django 3.2.13 on 2022-08-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    """add `reason` to Relationship model."""

    dependencies = [
        ('patients', '0005_patient_add_insurance_sex_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='reason',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='Reason of Status Change'),
        ),
    ]
