# Generated by Django 3.2.14 on 2022-08-31 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """Rename field health insurance number to ramq."""

    dependencies = [
        ('patients', '0006_relationship_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='health_insurance_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='ramq',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.RegexValidator('^[A-Z]{4}\\d{8}', 'First 4 characters should be alphabetic, last 8 characters should be numeric.')], verbose_name='RAMQ Number'),
        ),
    ]
