# Generated by Django 3.2.16 on 2022-11-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patient_hin_to_ramq'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('patient', 'caregiver', 'type', 'status'), name='unique_relationship'),
        ),
    ]
