# SPDX-FileCopyrightText: Copyright (C) 2022 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 3.2.16 on 2022-11-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add unique constraint to Relationship model."""

    dependencies = [
        ('patients', '0007_patient_hin_to_ramq'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(
                fields=('patient', 'caregiver', 'type', 'status'), name='patients_relationship_unique_constraint'
            ),
        ),
    ]
