# Generated by Django 3.2.14 on 2022-10-14 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add phone number field to the model."""

    dependencies = [
        ('patients', '0007_patient_hin_to_ramq'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: +<countryCode><phoneNumber> (for example +15141234567) with an optional extension "x123"', max_length=22, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{6,14}(x\\d{1,5})?$')], verbose_name='Phone Number'),
        ),
    ]
