# Generated by Django 3.2.16 on 2022-11-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add role type enum to Patients.RelationshipType, default 'Caregiver'."""

    dependencies = [
        ('patients', '0007_patient_hin_to_ramq'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshiptype',
            name='role_type',
            field=models.CharField(choices=[('SELF', 'Self'), ('CAREGIVER', 'Caregiver')], default='CAREGIVER', help_text='A "Self" role type indicates a patient who owns the data that is being accessed.', max_length=9, verbose_name='Relationship Role Type'),
        ),
    ]
