# Generated by Django 3.2.16 on 2022-11-21 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """Adds unique constraint to the `legacy_id` field of the `Patient` model."""

    dependencies = [
        ('patients', '0008_relationship_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Legacy ID'),
        ),
    ]
