# Generated by Django 3.2.16 on 2022-11-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add `date_of_death` field to Patient model."""

    dependencies = [
        ('patients', '0009_add_patient_legacy_id_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_death',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and Time of Death'),
        ),
    ]
