# Generated by Django 3.2.16 on 2022-12-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add role type enum to Patients.RelationshipType, default 'Caregiver'."""

    dependencies = [
        ('patients', '0009_add_patient_legacy_id_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshiptype',
            name='role_type',
            field=models.CharField(choices=[('SELF', 'Self'), ('CAREGIVER', 'Caregiver'), ('PARENTGUARDIAN', 'Parent/Guardian')], default='CAREGIVER', help_text='Role types track the category of relationship between a caregiver and patient. A "Self" role type indicates a patient who owns the data that is being accessed.', max_length=14, verbose_name='Relationship Role Type'),
        ),
    ]
