# Generated by Django 3.2.16 on 2022-12-01 17:20

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):
    """Add `date_of_death` field to Patient model."""

    dependencies = [
        ('patients', '0009_add_patient_legacy_id_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_death',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and Time of Death'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(check=models.Q(('date_of_birth__lte', django.db.models.expressions.F('date_of_death'))), name='patients_patient_date_valid'),
        ),
    ]
