# Generated by Django 3.2.16 on 2022-12-02 15:18
from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from opal.patients.models import RoleType
from opal.patients import constants


def generate_restricted_roletypes(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Generate the restricted role type objects and save to database."""
    RelationshipType = apps.get_model('patients', 'RelationshipType')
    # Clear before migrating to avoid pytest duplicate keys error
    RelationshipType.objects.filter(role_type__in={RoleType.SELF, RoleType.PARENTGUARDIAN}).delete()

    relationship_type_self = RelationshipType.objects.create(
        name='self',
        name_en='Self',
        name_fr='Soi',
        description_en='The patient is the requestor',
        description_fr='Le patient est le demandeur',
        start_age=14,
        role_type=RoleType.SELF,
    )
    relationship_type_self.save()
    relationship_type_parentguardian = RelationshipType.objects.create(
        name='parent/guardian',
        name_en='Guardian',
        name_fr='Gardien',
        description_en='A parent or guardian of the patient',
        description_fr='Un parent ou un tuteur du patient',
        start_age=constants.RELATIONSHIP_MIN_AGE,
        end_age=14,
        role_type=RoleType.PARENTGUARDIAN,
    )
    relationship_type_parentguardian.save()


def delete_restricted_roletypes(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Remove the restricted role type objects (for reverse migrations) and save database state."""
    RelationshipType = apps.get_model('patients', 'RelationshipType')
    RelationshipType.objects.filter(role_type__in={RoleType.SELF, RoleType.PARENTGUARDIAN}).delete()


class Migration(migrations.Migration):
    """Pre-populate deployment with the SELF and PARENTGUARDIAN role types."""

    dependencies = [
        ('patients', '0010_relationshiptype_role'),
    ]

    operations = [
        migrations.RunPython(generate_restricted_roletypes, reverse_code=delete_restricted_roletypes),
    ]
