# SPDX-FileCopyrightText: Copyright (C) 2022 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 3.2.16 on 2022-12-04 21:43

from django.db import migrations


class Migration(migrations.Migration):
    """Add `can_manage_relationships` permission to Patient model."""

    dependencies = [
        ('patients', '0011_patient_date_of_death'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={
                'permissions': (('can_manage_relationships', 'Can manage relationships'),),
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
            },
        ),
    ]
