# Generated by Django 3.2.16 on 2023-01-15 21:37

from django.db import migrations


class Migration(migrations.Migration):
    """Merge add new relationshiptype permissions and prepopulate relationshiptype."""

    dependencies = [
        ('patients', '0013_add_new_relationshiptypes_permission'),
        ('patients', '0014_prepopulate_relationshiptype'),
    ]

    operations = [
    ]
