# Generated by Django 3.2.16 on 2023-01-13 17:23

from django.db import migrations


class Migration(migrations.Migration):
    """Add unique constraint to `HospitalPatient` for `patient` and `site`."""

    dependencies = [
        ('hospital_settings', '0010_add_manage_institution_permission'),
        ('patients', '0014_prepopulate_relationshiptype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hospitalpatient',
            unique_together={('patient', 'site'), ('site', 'mrn')},
        ),
    ]
