# Generated by Django 3.2.16 on 2023-01-20 00:21

from django.db import migrations


class Migration(migrations.Migration):
    """Add `can_manage_relationshiptypes` permission to Patient model."""

    dependencies = [
        ('patients', '0015_hospitalpatient_unique_patient_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationshiptype',
            options={'ordering': ['name'], 'permissions': (('can_manage_relationshiptypes', 'Can manage relationship types'),), 'verbose_name': 'Caregiver Relationship Type', 'verbose_name_plural': 'Caregiver Relationship Types'},
        ),
    ]
