# Generated by Django 4.1.7 on 2023-05-04 15:39

from django.db import migrations


class Migration(migrations.Migration):
    """Add `can_perform_registration` permission to Relationship model."""

    dependencies = [
        ('patients', '0019_add_remaining_default_relationshiptypes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'permissions': (('can_manage_relationships', 'Can manage relationships'), ('can_perform_registration', 'Can perform registration')), 'verbose_name': 'Relationship', 'verbose_name_plural': 'Relationships'},
        ),
    ]
