# Generated by Django 4.1.7 on 2023-05-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    """Improve the verbose names of the `RelationshipType` model and its fields."""

    dependencies = [
        ('patients', '0020_update_manage_relationship_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationshiptype',
            options={
                'ordering': ['name'],
                'permissions': (
                    ('can_manage_relationshiptypes', 'Can manage relationship types'),
                ),
                'verbose_name': 'Relationship Type',
                'verbose_name_plural': 'Relationship Types',
            },
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='role_type',
            field=models.CharField(
                choices=[
                    ('SELF', 'Self'),
                    ('PARENTGUARDIAN', 'Parent/Guardian'),
                    ('GRDNCAREGIVER', 'Guardian-Caregiver'),
                    ('MANDATARY', 'Mandatary'),
                    ('CAREGIVER', 'Caregiver'),
                ],
                default='CAREGIVER',
                help_text='Role types track the category of relationship between a caregiver and patient. A "Self" role type indicates a patient who owns the data that is being accessed.',
                max_length=14,
                verbose_name='Role Type',
            ),
        ),
    ]
