# Generated by Django 4.1.7 on 2023-05-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    """Improve the verbose names of the `Relationship` model's fields."""

    dependencies = [
        ('patients', '0021_alter_relationshiptype_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='reason',
            field=models.CharField(
                blank=True,
                default='',
                max_length=255,
                verbose_name='Reason of Status Change',
            ),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='request_date',
            field=models.DateField(verbose_name='Request Date'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(
                choices=[
                    ('PEN', 'Pending'),
                    ('CON', 'Confirmed'),
                    ('DEN', 'Denied'),
                    ('EXP', 'Expired'),
                    ('REV', 'Revoked'),
                ],
                default='PEN',
                max_length=3,
                verbose_name='Status',
            ),
        ),
    ]
