# Generated by Django 4.1.7 on 2023-05-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add `data_access` to the `Patient` model to reflect the patient's desired level for data access."""

    dependencies = [
        ('patients', '0021_alter_relationshiptype_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='data_access',
            field=models.IntegerField(
                choices=[(1, 'All'), (2, 'Need To Know')],
                default=1,
                verbose_name='Data Access Level',
            ),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(
                check=models.Q(('data_access__in', [1, 2])),
                name='patients_patient_access_level_valid',
            ),
        ),
    ]
