# Generated by Django 4.1.9 on 2023-07-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add globally unique identifier field to DatabankConsent."""

    dependencies = [
        ('databank', '0003_alter_databankconsent_last_synchronized'),
    ]

    operations = [
        migrations.AddField(
            model_name='databankconsent',
            name='guid',
            field=models.CharField(default=None, max_length=64, unique=True, verbose_name='Globally Unique Identifier'),
            preserve_default=False,
        ),
    ]
