# Generated by Django 4.2.13 on 2024-06-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    """Create indexes on SharedData to aid querying large data table."""

    dependencies = [
        ('databank', '0004_databankconsent_guid'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shareddata',
            index=models.Index(fields=['sent_at'], name='shareddata_sent_at_idx'),
        ),
        migrations.AddIndex(
            model_name='shareddata',
            index=models.Index(fields=['databank_consent', 'sent_at'], name='shareddata_db_consent_sent_idx'),
        ),
    ]
