# SPDX-FileCopyrightText: Copyright (C) 2021 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 3.2.10 on 2021-12-21 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Initial migration that creates the Institution and Site models."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('parking_url', models.URLField(verbose_name='Parking Info')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('parking_url', models.URLField(verbose_name='Parking Info (URL)')),
                (
                    'institution',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sites',
                        to='hospital_settings.institution',
                        verbose_name='Institution',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
