# Generated by Django 3.2.10 on 2022-01-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Improve Institution and Site models.

    - Add default ordering
    - Remove parking_url from Institution
    - Make Institution and Site codes unique
    """

    dependencies = [
        ('hospital_settings', '0002_auto_20211222_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='institution',
            name='parking_url',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='parking_url_en',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='parking_url_fr',
        ),
        migrations.AlterField(
            model_name='institution',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='site',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code'),
        ),
    ]
