# Generated by Django 3.2.12 on 2022-04-11 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add caregiver relationships table."""

    dependencies = [
        ('hospital_settings', '0004_add_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverRelationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('name_en', models.CharField(max_length=25, null=True)),
                ('name_fr', models.CharField(max_length=25, null=True)),
                ('description', models.CharField(max_length=200)),
                ('description_en', models.CharField(max_length=200, null=True)),
                ('description_fr', models.CharField(max_length=200, null=True)),
                ('start_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('end_age', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('form_required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Caregiver Relationship',
                'verbose_name_plural': 'Caregiver Relationships',
                'ordering': ['name'],
            },
        ),
    ]
