# Generated by Django 3.2.12 on 2022-03-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """Update `Site` model: add direction_url field."""

    dependencies = [
        ('hospital_settings', '0004_add_verbose_name_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='direction_url',
            field=models.URLField(default=None, verbose_name='Direction Info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='direction_url_en',
            field=models.URLField(null=True, verbose_name='Direction Info'),
        ),
        migrations.AddField(
            model_name='site',
            name='direction_url_fr',
            field=models.URLField(null=True, verbose_name='Direction Info'),
        ),
    ]
