# Generated by Django 3.2.12 on 2022-04-12 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """Make User Patient Relationship Type table."""

    dependencies = [
        ('hospital_settings', '0004_add_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPatientRelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('name_en', models.CharField(max_length=25, null=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=25, null=True, verbose_name='Name')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('description_en', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('description_fr', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('start_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='Start age')),
                ('end_age', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='End age')),
                ('form_required', models.BooleanField(default=False, verbose_name='Form required')),
            ],
            options={
                'verbose_name': 'Caregiver Relationship',
                'verbose_name_plural': 'Caregiver Relationships',
                'ordering': ['name'],
            },
        ),
    ]
