# Generated by Django 3.2.13 on 2022-06-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    """Update `Site` model: add gps fields - longitude and latitude."""

    dependencies = [
        ('hospital_settings', '0005_add_site_direction_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=None, max_digits=22, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=None, max_digits=22, verbose_name='Longitude'),
        ),
    ]
