# SPDX-FileCopyrightText: Copyright (C) 2022 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 3.2.13 on 2022-07-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    """Update `Institution` model: add logo field."""

    dependencies = [
        ('hospital_settings', '0006_add_gps_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(default=None, upload_to='uploads/institution-logo/', verbose_name='Logo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='logo_en',
            field=models.ImageField(null=True, upload_to='uploads/institution-logo/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='institution',
            name='logo_fr',
            field=models.ImageField(null=True, upload_to='uploads/institution-logo/', verbose_name='Logo'),
        ),
    ]
