# Generated by Django 3.2.14 on 2022-08-18 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """Update `Institution` model: add term of use file(pdf) fields."""

    dependencies = [
        ('hospital_settings', '0006_add_gps_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='term_of_use',
            field=models.FileField(default=None, upload_to='uploads/% Y/% m/% d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
            preserve_default=False,
        ),
    ]
