# SPDX-FileCopyrightText: Copyright (C) 2022 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 3.2.15 on 2022-09-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add `support_email` field to the `Institution` model."""

    dependencies = [
        ('hospital_settings', '0008_add_terms_of_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='support_email',
            field=models.EmailField(default='opal@muhc.mcgill.ca', max_length=254, verbose_name='Support email'),
            preserve_default=False,
        ),
    ]
