# SPDX-FileCopyrightText: Copyright (C) 2023 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 3.2.16 on 2022-12-26 22:41

from django.db import migrations


class Migration(migrations.Migration):
    """Add `can_manage_sites` to the `Site` model."""

    dependencies = [
        ('hospital_settings', '0010_add_manage_institution_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={
                'ordering': ['name'],
                'permissions': (('can_manage_sites', 'Can manage sites'),),
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
    ]
