# Generated by Django 4.1.9 on 2023-07-13 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add `adulthood_age`, `interpretable_lab_result_delay` and `non_interpretable_lab_result_delay` fields to the `Institution` model."""

    dependencies = [
        ('hospital_settings', '0011_add_manage_site_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='adulthood_age',
            field=models.PositiveIntegerField(default=18, help_text='Age setting used to control pediatric functionality which delays sharing of lab results.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Adulthood Age'),
        ),
        migrations.AddField(
            model_name='institution',
            name='interpretable_lab_result_delay',
            field=models.PositiveIntegerField(default=0, help_text='Lab result delay for pediatric patients when clinician interpretation is not specified in lab setting.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Interpretable Lab Result Delay'),
        ),
        migrations.AddField(
            model_name='institution',
            name='non_interpretable_lab_result_delay',
            field=models.PositiveIntegerField(default=0, help_text='Lab result delay for pediatric patients when clinician interpretation is recommended in lab setting.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Non-Interpretable Lab Result Delay'),
        ),
    ]
