# Generated by Django 4.1.11 on 2023-09-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add address fields to the `Site` model."""

    dependencies = [
        ('hospital_settings', '0012_add_delay_fields_for_labs'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='contact_fax',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Fax'),
        ),
        migrations.AddField(
            model_name='site',
            name='contact_telephone',
            field=models.CharField(default='', max_length=100, verbose_name='Contact Telephone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='postal_code',
            field=models.CharField(default='', max_length=6, verbose_name='Postal Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='province_code',
            field=models.CharField(default='', max_length=2, verbose_name='Province Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='street_name',
            field=models.CharField(default='', max_length=100, verbose_name='Street Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='street_number',
            field=models.CharField(default='', max_length=100, verbose_name='Street Number'),
            preserve_default=False,
        ),
    ]
