# Generated by Django 4.1.13 on 2023-11-16 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to improve the registration code valid period."""

    dependencies = [
        ('hospital_settings', '0014_add_reg_code_valid_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='registration_code_valid_period',
            field=models.PositiveIntegerField(
                default=24,
                help_text='How many hours a registration code is valid for.',
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(72),
                ],
                verbose_name='Registration Code Valid Period',
            ),
        ),
    ]
