# Generated by Django 4.1.12 on 2023-10-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add `acronym` field to the `Institution` model instead of `code`."""

    dependencies = [
        ('hospital_settings', '0014_add_reg_code_valid_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='acronym',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='Acronym'),
        ),
    ]
