# SPDX-FileCopyrightText: Copyright (C) 2023 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 4.1.12 on 2023-10-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Rename the field `code`  to `acronym` for the `location` model.

    Add the field translations.
    """

    dependencies = [
        ('hospital_settings', '0015_alter_institution_registration_code_validity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='code',
            new_name='acronym',
        ),
        migrations.AlterField(
            model_name='institution',
            name='acronym',
            field=models.CharField(max_length=10, unique=True, verbose_name='Acronym'),
        ),
        migrations.RenameField(
            model_name='site',
            old_name='code',
            new_name='acronym',
        ),
        migrations.AlterField(
            model_name='site',
            name='acronym',
            field=models.CharField(max_length=10, unique=True, verbose_name='Acronym'),
        ),
        migrations.AddField(
            model_name='institution',
            name='acronym_en',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Acronym'),
        ),
        migrations.AddField(
            model_name='institution',
            name='acronym_fr',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Acronym'),
        ),
        migrations.AddField(
            model_name='site',
            name='acronym_en',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Acronym'),
        ),
        migrations.AddField(
            model_name='site',
            name='acronym_fr',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Acronym'),
        ),
    ]
