# Generated by Django 4.1.12 on 2023-10-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    """Rename the field `code`  to `acronym` for the `location` model."""

    dependencies = [
        ('hospital_settings', '0015_alter_institution_registration_code_validity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='code',
        ),
        migrations.RemoveField(
            model_name='site',
            name='code',
        ),
        migrations.AddField(
            model_name='institution',
            name='acronym',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='Acronym'),
        ),
        migrations.AddField(
            model_name='site',
            name='acronym',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='Acronym'),
        ),
    ]
