# Generated by Django 3.2.13 on 2022-06-17 06:22

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):
    """Add SecurityQuestion and SecurityAnswer models."""

    dependencies = [
        ('caregivers', '0001_caregiverprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=2056, verbose_name='Security Answer')),
                ('created_at', models.DateField(verbose_name='Creation Date')),
                ('updated_at', models.DateField(verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Security Answer',
                'verbose_name_plural': 'Security Answers',
            },
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(max_length=2056, verbose_name='Question Text EN')),
                ('question_fr', models.CharField(max_length=2056, verbose_name='Question Text FR')),
                ('created_at', models.DateField(verbose_name='Creation Date')),
                ('updated_at', models.DateField(verbose_name='Last Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Security Question',
                'verbose_name_plural': 'Security Questions',
            },
        ),
        migrations.AddConstraint(
            model_name='securityquestion',
            constraint=models.CheckConstraint(check=models.Q(('created_at__lte', django.db.models.expressions.F('updated_at'))), name='caregivers_securityquestion_date_valid'),
        ),
        migrations.AddField(
            model_name='securityanswer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_answers', to='caregivers.caregiverprofile', verbose_name='Caregiver Profile'),
        ),
        migrations.AddField(
            model_name='securityanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_answers', to='caregivers.securityquestion', verbose_name='Security Question'),
        ),
        migrations.AddConstraint(
            model_name='securityanswer',
            constraint=models.CheckConstraint(check=models.Q(('created_at__lte', django.db.models.expressions.F('updated_at'))), name='caregivers_securityanswer_date_valid'),
        ),
    ]
