# Generated by Django 3.2.14 on 2022-07-29 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    """Add uuid field to caregiver profile model."""

    dependencies = [
        ('caregivers', '0003_securityquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='universally unique identifier'),
        ),
    ]
