# Generated by Django 3.2.16 on 2022-10-05 02:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Add EmailVerification model."""

    dependencies = [
        ('caregivers', '0005_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Verification Code')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verfied')),
                ('sent_at', models.DateTimeField(null=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='caregivers.caregiverprofile', verbose_name='Caregiver Profile')),
            ],
            options={
                'verbose_name': 'Email Verification Code',
                'verbose_name_plural': 'Email Verification Codes',
            },
        ),
    ]
