# Generated by Django 3.2.16 on 2022-10-05 02:42

from django.db import migrations


class Migration(migrations.Migration):
    """Remove the field email verification code from model RegistrationCode."""

    dependencies = [
        ('caregivers', '0006_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationcode',
            name='email_verification_code',
        ),
    ]
