# Generated by Django 3.2.16 on 2022-10-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    """Update device to include push_token and modified fields."""

    dependencies = [
        ('caregivers', '0006_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
        migrations.AddField(
            model_name='device',
            name='push_token',
            field=models.CharField(blank=True, max_length=256, verbose_name='Push Token'),
        ),
    ]
