# Generated by Django 3.2.16 on 2022-11-22 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """Adds unique constraint to the `legacy_id` field of the `CaregiverProfile` model."""

    dependencies = [
        ('caregivers', '0007_device_push_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverprofile',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Legacy ID'),
        ),
    ]
