# Generated by Django 3.2.18 on 2023-03-02 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    """Update `creation_date` field to `created_at` and change its type to `DateTimeField`."""

    dependencies = [
        ('caregivers', '0008_modify_caregiverprofile_legacyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationcode',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='registrationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
    ]
