{
    'duration': 'INDEF',
    'effective_at': datetime.datetime(2023, 12, 6, 10, 0, tzinfo=zoneinfo.ZoneInfo(key='America/Toronto')),
    'entered_at': datetime.datetime(2023, 12, 6, 13, 16, 10, tzinfo=zoneinfo.ZoneInfo(key='America/Toronto')),
    'entered_by': 'Marc-Alexandre_Duceppe_MDUCEPPE',
    'filler_order_number': '25008915',
    'interval_duration': '1000',
    'interval_pattern': 'Q24',
    'order_status': 'SC',
    'ordered_by': 'Dr._Emergency_100000',
    'pharmacy_encoded_order': {
        'dispense_amount': '50',
        'dispense_units': 'MG',
        'duration': 'INDEF',
        'formulary_status': 'STD',
        'give_amount_maximum': '50',
        'give_amount_minimum': '',
        'give_code': {
            'alternate_coding_system': 'AHFS',
            'alternate_identifier': '20:12.04',
            'alternate_text': 'ANTICOAGULANTS',
            'coding_system': 'RXTFC',
            'identifier': 'ENOXAREDES100I3',
            'text': 'ENOXAPARIN (REDESCA) IJ',
        },
        'give_dosage_form': {
            'coding_system': 'RxTFC',
            'identifier': 'INJVIAL',
            'text': 'VIAL INJ',
        },
        'give_units': 'MG',
        'interval_duration': '1000',
        'interval_pattern': 'Q24',
        'pharmacy_components': [{'component_amount': '50',
                                'component_code': {'alternate_coding_system': 'AHFS',
                                                    'alternate_identifier': '20:12.04',
                                                    'alternate_text': 'ANTICOAGULANTS',
                                                    'coding_system': 'RXTFC',
                                                    'identifier': 'ENOXAREDES100I3',
                                                    'text': 'ENOXAPARIN '
                                                            '(REDESCA)'},
                                'component_type': 'A',
                                'component_units': 'MG'},
                                {'component_amount': '0',
                                'component_code': {'alternate_coding_system': 'AHFS',
                                                    'alternate_identifier': '',
                                                    'alternate_text': '',
                                                    'coding_system': 'RXTFC',
                                                    'identifier': 'FT',
                                                    'text': 'SC '
                                                            'Q24H'},
                                'component_type': 'T',
                                'component_units': ''},
                                {'component_amount': '0',
                                'component_code': {'alternate_coding_system': 'AHFS',
                                                    'alternate_identifier': '',
                                                    'alternate_text': '',
                                                    'coding_system': 'RXTFC',
                                                    'identifier': 'FT',
                                                    'text': 'SUBCUTANEOUSLY'},
                                'component_type': 'T',
                                'component_units': ''},
                                {'component_amount': '0',
                                'component_code': {'alternate_coding_system': 'AHFS',
                                                    'alternate_identifier': '',
                                                    'alternate_text': '',
                                                    'coding_system': 'RXTFC',
                                                    'identifier': 'RT',
                                                    'text': 'KEEP '
                                                            'AT '
                                                            'ROOM '
                                                            'TEMPERATURE'},
                                'component_type': 'T',
                                'component_units': ''},
                                {'component_amount': '0',
                                'component_code': {'alternate_coding_system': 'AHFS',
                                                    'alternate_identifier': '',
                                                    'alternate_text': '',
                                                    'coding_system': 'RXTFC',
                                                    'identifier': 'FT',
                                                    'text': 'PREPARED '
                                                            'BY '
                                                            'PHARMACY '
                                                            'FROM '
                                                            'VIAL'},
                                'component_type': 'T',
                                'component_units': ''},
                                {'component_amount': '0',
                                'component_code': {'alternate_coding_system': 'AHFS',
                                                    'alternate_identifier': '',
                                                    'alternate_text': '',
                                                    'coding_system': 'RXTFC',
                                                    'identifier': 'FT',
                                                    'text': 'BLEEDING '
                                                            'RISK- '
                                                            'ANTICOAGULANT'},
                                'component_type': 'T',
                                'component_units': ''},
                                {'component_amount': '0',
                                'component_code': {'alternate_coding_system': 'AHFS',
                                                    'alternate_identifier': '',
                                                    'alternate_text': '',
                                                    'coding_system': 'RXTFC',
                                                    'identifier': 'HA',
                                                    'text': '*HIGH '
                                                            'ALERT*'},
                                'component_type': 'T',
                                'component_units': ''}],
        'pharmacy_route': {'administration_device': '',
                            'administration_method': {'alternate_coding_system': '',
                                                    'alternate_identifier': '',
                                                    'alternate_text': '',
                                                    'coding_system': 'RxTFC',
                                                    'identifier': 'IJ',
                                                    'text': 'Inj '
                                                            'Syringe'},
                            'route': {'alternate_coding_system': '',
                                    'alternate_identifier': '',
                                    'alternate_text': '',
                                    'coding_system': 'RxTFC',
                                    'identifier': 'SCMED',
                                    'text': 'SC Injection '
                                            '(Med Order)'},
                            'site': ''},
        'priority': 'R',
        'provider_administration_instruction': '50 mg = '
                                                '0.5 mL SC '
                                                'Q24H \n'
                                                'BLEEDING '
                                                'RISK- '
                                                'ANTICOAGULANT\n'
                                                '* HIGH '
                                                'ALERT  *',
        'quantity': '0.17',
        'refills': '0.00',
        'refills_remaining': '0.000',
        'service_end': datetime.datetime(2024, 12, 5, 18, 59, tzinfo=zoneinfo.ZoneInfo(key='America/Toronto')),
        'service_start': datetime.datetime(2023, 12, 6, 10, 0, tzinfo=zoneinfo.ZoneInfo(key='America/Toronto')),
        'unit': ''},
    'priority': 'R',
    'quantity': '0.17',
    'service_end': datetime.datetime(2024, 12, 5, 18, 59, tzinfo=zoneinfo.ZoneInfo(key='America/Toronto')),
    'service_start': datetime.datetime(2023, 12, 6, 10, 0, tzinfo=zoneinfo.ZoneInfo(key='America/Toronto')),
    'trigger_event': 'XX',
    'unit': '',
    'verified_by': 'Marc-Alexandre_Duceppe_MDUCEPPE',
    'visit_number': '000002050173412'
}
