# Generated by Django 4.1.13 on 2024-03-05 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Update models after additional gateway pharmacy message testing identified several issues.

    Fixes several issues in the models:
        - Split abstract interval into interval_pattern and interval_duration
        - Change CodedElement foreign key to Charfield for several fields in RXE, RXC, and RXR
        - Fix the uniqueness constraint on CodedElement
        - Drop last_refilled field (always omitted in gateway messages)
        - Make the related_name for the OneToOneField less verbose to improve readability
    """

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacyencodedorder',
            old_name='interval',
            new_name='interval_pattern',
        ),
        migrations.RenameField(
            model_name='physicianprescriptionorder',
            old_name='interval',
            new_name='interval_pattern',
        ),
        migrations.RemoveField(
            model_name='pharmacyencodedorder',
            name='last_refilled',
        ),
        migrations.AddField(
            model_name='pharmacyencodedorder',
            name='interval_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='physicianprescriptionorder',
            name='interval_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacycomponent',
            name='component_units',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmacycomponent',
            name='pharmacy_encoded_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_components', to='pharmacy.pharmacyencodedorder'),
        ),
        migrations.AlterField(
            model_name='pharmacyencodedorder',
            name='dispense_units',
            field=models.CharField(blank=True, default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmacyencodedorder',
            name='give_units',
            field=models.CharField(blank=True, default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmacyencodedorder',
            name='physician_prescription_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_encoded_order', to='pharmacy.physicianprescriptionorder'),
        ),
        migrations.AlterField(
            model_name='pharmacyencodedorder',
            name='provider_administration_instruction',
            field=models.CharField(blank=True, default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmacyroute',
            name='administration_device',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmacyroute',
            name='pharmacy_encoded_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_route', to='pharmacy.pharmacyencodedorder'),
        ),
        migrations.AlterField(
            model_name='pharmacyroute',
            name='site',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='codedelement',
            unique_together={('identifier', 'text', 'coding_system')},
        ),
    ]
