# Generated by Django 4.1.13 on 2024-03-07 13:50

from django.db import migrations


class Migration(migrations.Migration):
    """Drop refills_remaining from the RXE model as too many messages have been found to be missing it during testing."""

    dependencies = [
        ('pharmacy', '0002_fix_uniqueness_constraint_and_codedelement_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyencodedorder',
            name='refills_remaining',
        ),
    ]
