# Generated by Django 4.1.13 on 2024-02-21 20:10

from django.db import migrations


class Migration(migrations.Migration):
    """Fix `CodedElement` uniqueness constraint and drop last_refilled."""

    dependencies = [
        ('pharmacy', '0002_reduce_coded_element_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyencodedorder',
            name='last_refilled',
        ),
        migrations.AlterUniqueTogether(
            name='codedelement',
            unique_together={('identifier', 'text', 'coding_system')},
        ),
    ]
