# Generated by Django 4.1.13 on 2024-03-05 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Fix `CodedElement` uniqueness constraint, drop last_refilled, and allow dispense_unit blank."""

    dependencies = [
        ('pharmacy', '0002_reduce_coded_element_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyencodedorder',
            name='last_refilled',
        ),
        migrations.AlterField(
            model_name='pharmacyencodedorder',
            name='dispense_units',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='pharmacyencodedorder',
            name='physician_prescription_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_encoded_order', to='pharmacy.physicianprescriptionorder'),
        ),
        migrations.AlterUniqueTogether(
            name='codedelement',
            unique_together={('identifier', 'text', 'coding_system')},
        ),
    ]
