# SPDX-FileCopyrightText: Copyright (C) 2025 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
name: build

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
          lfs: true
      - uses: opalmedapps/.github/.github/actions/docker-build@main
        id: build-image
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ env.IMAGE_NAME }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # create minimal env file for testing the image
      - name: Prepare environment
        run: |
          cp .env.sample .env
          # generate secret key
          SECRET_KEY=$(python -c "import secrets; print(secrets.token_urlsafe())")
          sed -i "s/^SECRET_KEY=.*/SECRET_KEY=$SECRET_KEY/" .env
      - name: Test the image
        env:
          TAG: ${{ steps.build-image.outputs.tag }}
        # ensure that gunicorn is installed and that simple checks pass
        run: docker run --rm --env-file .env "$TAG" sh -c "gunicorn --version && python manage.py check"
