# SPDX-FileCopyrightText: Copyright (C) 2025 Opal Health Informatics Group <https://www.opalmedapps.com>
#
# SPDX-License-Identifier: MIT
name: npm-update

on:
  pull_request:
    paths:
      - opal/static/thirdparty/package.json
      - opal/static/thirdparty/package-lock.json

permissions:
  contents: write

jobs:
  npm-update:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'renovate[bot]' && github.repository == github.event.pull_request.head.repo.full_name
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: true
      - name: Configure Git Credentials
        # see: https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: |
          cd opal/static/thirdparty/
          npm install
          git log
          git add .
          git commit -m "update static thirdparty files"
          git push origin HEAD:
